# Generated by Django 3.1.7 on 2021-03-24 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fare_cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingdetails',
            name='line_color',
            field=models.CharField(default=datetime.datetime(2021, 3, 24, 12, 30, 10, 745762, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
