# Generated by Django 3.1.7 on 2021-03-24 14:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fare_cal', '0003_auto_20210324_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingdetail',
            name='boarding_id',
            field=models.CharField(default=datetime.datetime(2021, 3, 24, 14, 23, 36, 828209, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
